name: Deployment

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - "develop"

jobs:
  publish:
    name: Test publish package
    runs-on: ubuntu-latest
    environment: "test_deployment"

    steps:
      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v1.10
