on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
        default: https://pypi.python.org/simple/

      token:
        required: true
        type: string

      python_version:
        required: true
        default: 3.9
        type: string

      poetry_version:
        required: true
        default: 1.1.12
        type: string

      install_deps:
        type: string
        default: true
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish python package
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}

      - uses: actions/checkout@v2
      - run: pip install --upgrade pip poetry
      - run: |
          poetry config repositories.destrepo ${{ secrets.url }}
          poetry config pypi-token.destrepo ${{ secrets.token }}
          poetry config virtualenvs.create false
        name: Configure poetry
      - name: Install project dependencies
        run: |
          poetry install $(test "$INSTALL_DEPS" != "true" && echo --no-dev)
      - run: poetry build
        name: Build package
      - run: poetry publish -r destrepo
